import type { Skin } from '@/types'

export const defaultSkin: Skin = {
  id: 'default',
  name: 'Padrão',
  icon: '💬',
  layout: 'bubble',
  avatarShape: 'round',
  light: {
    '--bg-main': '#f8fafc',
    '--bg-sidebar': '#f1f5f9',
    '--bg-header': '#ffffff',
    '--bg-input': '#ffffff',
    '--bg-bubble-sent': '#3b82f6',
    '--bg-bubble-received': '#ffffff',
    '--text-primary': '#0f172a',
    '--text-secondary': '#64748b',
    '--text-bubble-sent': '#ffffff',
    '--text-bubble-received': '#0f172a',
    '--accent': '#3b82f6',
    '--accent-fg': '#ffffff',
    '--border-color': '#e2e8f0',
    '--name-color': '#3b82f6',
    '--header-fg': '#0f172a',
  },
  dark: {
    '--bg-main': '#0f172a',
    '--bg-sidebar': '#1e293b',
    '--bg-header': '#1e293b',
    '--bg-input': '#1e293b',
    '--bg-bubble-sent': '#3b82f6',
    '--bg-bubble-received': '#334155',
    '--text-primary': '#f1f5f9',
    '--text-secondary': '#94a3b8',
    '--text-bubble-sent': '#ffffff',
    '--text-bubble-received': '#f1f5f9',
    '--accent': '#60a5fa',
    '--accent-fg': '#ffffff',
    '--border-color': '#334155',
    '--name-color': '#60a5fa',
    '--header-fg': '#f1f5f9',
  },
}
