import type { Skin } from '@/types'

export const discordSkin: Skin = {
  id: 'discord',
  name: 'Discord',
  icon: '🎮',
  layout: 'flat',
  avatarShape: 'round',
  light: {
    '--bg-main': '#ffffff',
    '--bg-sidebar': '#f2f3f5',
    '--bg-header': '#ffffff',
    '--bg-input': '#ebedef',
    '--bg-bubble-sent': 'transparent',
    '--bg-bubble-received': 'transparent',
    '--text-primary': '#2e3338',
    '--text-secondary': '#72767d',
    '--text-bubble-sent': '#2e3338',
    '--text-bubble-received': '#2e3338',
    '--accent': '#5865f2',
    '--accent-fg': '#ffffff',
    '--border-color': '#e3e5e8',
    '--name-color': '#5865f2',
    '--header-fg': '#2e3338',
  },
  dark: {
    '--bg-main': '#313338',
    '--bg-sidebar': '#2b2d31',
    '--bg-header': '#313338',
    '--bg-input': '#383a40',
    '--bg-bubble-sent': 'transparent',
    '--bg-bubble-received': 'transparent',
    '--text-primary': '#dbdee1',
    '--text-secondary': '#949ba4',
    '--text-bubble-sent': '#dbdee1',
    '--text-bubble-received': '#dbdee1',
    '--accent': '#5865f2',
    '--accent-fg': '#ffffff',
    '--border-color': '#3f4147',
    '--name-color': '#5865f2',
    '--header-fg': '#dbdee1',
  },
}
