import type { Skin } from '@/types'

export const slackSkin: Skin = {
  id: 'slack',
  name: 'Slack',
  icon: '#',
  layout: 'flat',
  avatarShape: 'square',
  light: {
    '--bg-main': '#ffffff',
    '--bg-sidebar': '#3f0e40',
    '--bg-header': '#ffffff',
    '--bg-input': '#ffffff',
    '--bg-bubble-sent': 'transparent',
    '--bg-bubble-received': 'transparent',
    '--text-primary': '#1d1c1d',
    '--text-secondary': '#616061',
    '--text-bubble-sent': '#1d1c1d',
    '--text-bubble-received': '#1d1c1d',
    '--accent': '#1264a3',
    '--accent-fg': '#ffffff',
    '--border-color': '#e8e8e8',
    '--name-color': '#1264a3',
    '--header-fg': '#1d1c1d',
  },
  dark: {
    '--bg-main': '#1a1d21',
    '--bg-sidebar': '#19171d',
    '--bg-header': '#1a1d21',
    '--bg-input': '#282c35',
    '--bg-bubble-sent': 'transparent',
    '--bg-bubble-received': 'transparent',
    '--text-primary': '#d1d2d3',
    '--text-secondary': '#ababad',
    '--text-bubble-sent': '#d1d2d3',
    '--text-bubble-received': '#d1d2d3',
    '--accent': '#1d9bd1',
    '--accent-fg': '#ffffff',
    '--border-color': '#3d3f40',
    '--name-color': '#1d9bd1',
    '--header-fg': '#d1d2d3',
  },
}
