import type { Skin } from '@/types'

/** Visual Microsoft Teams — skin Premium */
export const teamsSkin: Skin = {
  id: 'teams',
  name: 'Microsoft Teams',
  icon: 'Ⓜ️',
  layout: 'bubble',
  avatarShape: 'round',
  chrome: 'teams',
  light: {
    '--bg-main': '#ffffff',
    '--bg-sidebar': '#ffffff',
    '--bg-header': '#ffffff',
    '--bg-input': '#ffffff',
    '--bg-bubble-sent': '#e5deff',
    '--bg-bubble-received': '#f5f5f5',
    '--text-primary': '#242424',
    '--text-secondary': '#616161',
    '--text-bubble-sent': '#242424',
    '--text-bubble-received': '#242424',
    '--accent': '#5b5fc7',
    '--accent-fg': '#ffffff',
    '--border-color': '#edebe9',
    '--name-color': '#5b5fc7',
    '--header-fg': '#242424',
  },
  dark: {
    '--bg-main': '#1f1f1f',
    '--bg-sidebar': '#292929',
    '--bg-header': '#292929',
    '--bg-input': '#292929',
    '--bg-bubble-sent': '#4f52b2',
    '--bg-bubble-received': '#3d3d3d',
    '--text-primary': '#ffffff',
    '--text-secondary': '#adadad',
    '--text-bubble-sent': '#ffffff',
    '--text-bubble-received': '#ffffff',
    '--accent': '#7b7ff7',
    '--accent-fg': '#ffffff',
    '--border-color': '#3d3d3d',
    '--name-color': '#7b7ff7',
    '--header-fg': '#ffffff',
  },
}
