import type { Skin } from '@/types'

export const telegramSkin: Skin = {
  id: 'telegram',
  name: 'Telegram',
  icon: '✈️',
  layout: 'bubble',
  avatarShape: 'round',
  light: {
    '--bg-main': '#efeff3',
    '--bg-sidebar': '#ffffff',
    '--bg-header': '#517da2',
    '--bg-input': '#ffffff',
    '--bg-bubble-sent': '#effdde',
    '--bg-bubble-received': '#ffffff',
    '--text-primary': '#000000',
    '--text-secondary': '#707579',
    '--text-bubble-sent': '#000000',
    '--text-bubble-received': '#000000',
    '--accent': '#2aabee',
    '--accent-fg': '#ffffff',
    '--border-color': '#dae1e7',
    '--name-color': '#2aabee',
    '--header-fg': '#ffffff',
  },
  dark: {
    '--bg-main': '#0e1621',
    '--bg-sidebar': '#17212b',
    '--bg-header': '#17212b',
    '--bg-input': '#17212b',
    '--bg-bubble-sent': '#2b5278',
    '--bg-bubble-received': '#182533',
    '--text-primary': '#ffffff',
    '--text-secondary': '#708499',
    '--text-bubble-sent': '#ffffff',
    '--text-bubble-received': '#ffffff',
    '--accent': '#2aabee',
    '--accent-fg': '#ffffff',
    '--border-color': '#0e1621',
    '--name-color': '#2aabee',
    '--header-fg': '#ffffff',
  },
}
