import type { Skin } from '@/types'

export const whatsappSkin: Skin = {
  id: 'whatsapp',
  name: 'WhatsApp',
  icon: '📱',
  layout: 'bubble',
  avatarShape: 'round',
  light: {
    '--bg-main': '#e5ddd5',
    '--bg-sidebar': '#ffffff',
    '--bg-header': '#075e54',
    '--bg-input': '#ffffff',
    '--bg-bubble-sent': '#dcf8c6',
    '--bg-bubble-received': '#ffffff',
    '--text-primary': '#111b21',
    '--text-secondary': '#667781',
    '--text-bubble-sent': '#111b21',
    '--text-bubble-received': '#111b21',
    '--accent': '#25d366',
    '--accent-fg': '#ffffff',
    '--border-color': '#d1d7db',
    '--name-color': '#25d366',
    '--header-fg': '#ffffff',
  },
  dark: {
    '--bg-main': '#0b141a',
    '--bg-sidebar': '#111b21',
    '--bg-header': '#202c33',
    '--bg-input': '#2a3942',
    '--bg-bubble-sent': '#005c4b',
    '--bg-bubble-received': '#202c33',
    '--text-primary': '#e9edef',
    '--text-secondary': '#8696a0',
    '--text-bubble-sent': '#e9edef',
    '--text-bubble-received': '#e9edef',
    '--accent': '#00a884',
    '--accent-fg': '#111b21',
    '--border-color': '#2a3942',
    '--name-color': '#00a884',
    '--header-fg': '#e9edef',
  },
}
